### ISSUE TITLE
grattan failing to install

### ISSUE THREAD

**Issue by wfmackey** [HughParsonage/grattan#195] opened 2019-08-26 05:50 UTC
The `grattan` package is failing to install on a system that has not previously installed the package:

```
R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> remotes::install_github("hughparsonage/grattan")
Downloading GitHub repo hughparsonage/grattan@master
Your system is ready to build packages!
Installing 19 packages: hutils, ineq, rsdmx, fastmatch, forecast, zoo, XML, RCurl, fracdiff, lmtest, timeDate, tseries, urca, RcppArmadillo, bitops, quadprog, quantmod, xts, TTR
Error: Failed to install 'grattan' from GitHub:
  (converted from warning) unable to access index for repository https://hughparsonage.github.io/tax-drat/bin/macosx/el-capitan/contrib/3.6:
  cannot open URL 'https://hughparsonage.github.io/tax-drat/bin/macosx/el-capitan/contrib/3.6/PACKAGES'
> 
> 
```

The package is also failing to update the package on a system that had it installed, with the same warning:

```
R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin15.6.0 (64-bit)
 
R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.
 
  Natural language support but running in an English locale
 
R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.
 
Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.
 
> remotes::install_github("hughparsonage/grattan")
Downloading GitHub repo hughparsonage/grattan@master
These packages have more recent versions available.
Which would you like to update?
 
1: All                                                
 2: CRAN packages only                                  
 3: None                                               
 4: forecast     (8.4          -> 8.9         ) [CRAN] 
 5: lmtest       (0.9-36       -> 0.9-37      ) [CRAN] 
 6: tseries      (0.10-45      -> 0.10-47     ) [CRAN] 
 7: RcppArmad... (0.8.600.0.0  -> 0.9.600.4.0 ) [CRAN] 
 8: rlang        (09fbc8618... -> 15e799c57...) [GitHub]
9: vctrs        (6701f7816... -> 1cdd19df1...) [GitHub]
10: quadprog     (1.5-5        -> 1.5-7       ) [CRAN] 
11: quantmod     (0.4-13       -> 0.4-15      ) [CRAN] 
12: xts          (0.11-0       -> 0.11-2      ) [CRAN] 
13: TTR          (0.23-3       -> 0.23-4      ) [CRAN] 
 
Enter one or more numbers, or an empty line to skip updates:
1
forecast     (8.4          -> 8.9         ) [CRAN]
lmtest       (0.9-36       -> 0.9-37      ) [CRAN]
tseries      (0.10-45      -> 0.10-47     ) [CRAN]
RcppArmad... (0.8.600.0.0  -> 0.9.600.4.0 ) [CRAN]
rlang        (09fbc8618... -> 15e799c57...) [GitHub]
vctrs        (6701f7816... -> 1cdd19df1...) [GitHub]
quadprog     (1.5-5        -> 1.5-7       ) [CRAN]
quantmod     (0.4-13       -> 0.4-15      ) [CRAN]
xts          (0.11-0       -> 0.11-2      ) [CRAN]
TTR          (0.23-3       -> 0.23-4      ) [CRAN]
Installing 8 packages: forecast, lmtest, tseries, RcppArmadillo, quadprog, quantmod, xts, TTR
Installing packages into ‘/Users/mackeyw/Library/R/3.6/library’
(as ‘lib’ is unspecified)
Error: Failed to install 'grattan' from GitHub:
  (converted from warning) unable to access index for repository https://hughparsonage.github.io/tax-drat/bin/macosx/el-capitan/contrib/3.6:
  cannot open URL 'https://hughparsonage.github.io/tax-drat/bin/macosx/el-capitan/contrib/3.6/PACKAGES'
```

**Comment by MattCowgill** [comment] 2019-08-26 05:51
Also fails on my machine: 

remotes::install_github("hughparsonage/grattan", dependencies = TRUE)

fails with error:

Error: Failed to install 'grattan' from GitHub: (converted from warning) unable to access index for repository https://hughparsonage.github.io/tax-drat/bin/macosx/el-capitan/contrib/3.6: cannot open URL 'https://hughparsonage.github.io/tax-drat/bin/macosx/el-capitan/contrib/3.6/PACKAGES'

**Comment by HughParsonage** [comment] 2019-08-26 08:51
Does

```r
remotes::install_github("hughparsonage/grattan", dependencies = TRUE, type = "source")
```

work?

**Comment by MattCowgill** [comment] 2019-08-26 22:58
That failed several times at various points. Once I'd manually installed various dependencies (with `install.packages("future")` etc.) it then worked. I'll try on a fresh R install.

**Comment by HughParsonage** [comment] 2019-08-26 23:43
Looks like a bug in remotes

**Comment by MattCowgill** [comment] 2019-08-27 01:10
I tried a fresh install on a Windows 10 VM. Same issue - it failed (after about 40 minutes) trying to install a dependency (in this case RCurl).

**Comment by HughParsonage** [comment] 2019-08-27 01:21
What was the error message? I can't reproduce on any platform.

FWIW it's not an issue with the grattan package but with the logic of
installing dependencies.

What about

install.packages("grattan")
remote::install_packages("grattan", upgrade = "never")

**Comment by MattCowgill** [comment] 2019-08-27 01:24
This was the error: ![Screen Shot 2019-08-27 at 10 36 58 am](https://user-images.githubusercontent.com/8002951/63733773-0df45000-c8bd-11e9-8de5-02ba443752c6.png)

I think did:
`install.packages("RCurl")`

and repeated:

`remotes::install_github("hughparsonage/grattan", dependencies = NA, type = "source", upgrade = "never")`

and it worked

**Comment by HughParsonage** [comment] 2019-08-27 01:32
OK. The issue is that XML has a libxml2 SystemsRequirements which appears
to have been absent on that platform. So you need to install the win.binary
or mac.binary version. But if you request a binary on Mac, remotes only
looks for mac binaries throughout the tail of dependencies and there is no
taxstats mac binary.

IMO remotes should fall back to a source installation if it's available and
doesn't require compilation, though packages in AdditionalRepositories
appears to be a corner case.

**Comment by HughParsonage** [comment] 2019-08-27 05:08
To summarize, to install from GitHub, first install from CRAN then attempt a dependency-less install with no upgrades. That way, there is no attempt by `remotes` to install Suggested dependencies, in particular `taxstats` for which the binary not available for Mac.

**Comment by HughParsonage** [comment] 2019-09-03 12:31
Did you manage to install it?

In your opinion, do I need to change anything to fix the issue?

**Comment by MattCowgill** [comment] 2019-09-03 23:17
yes, it’s working, so I’ll close the issue. In the medium term we’ll try to think of ways to streamline some of the functions and make installation less heavy

**Closed by MattCowgill** 2019-09-03 23:17 UTC
